POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@j.com"
}

###

POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@j.com"
}


###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "6aeb66dd-0a20-4e12-8694-eecf457fe739"
}

###

POST http://localhost:3000/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "31168c15-b24c-409b-b9fa-693db404a9db",
    "account_id_to": "24b1b373-c52a-4687-9a71-10f60b61b4a4",
    "amount": 1
}

###

GET http://localhost:3003/balances/31168c15-b24c-409b-b9fa-693db404a9db

###

GET http://localhost:3003/balances/24b1b373-c52a-4687-9a71-10f60b61b4a4